service: test-service

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: src/api-gw/handler.hello
    events:
      - http:
          path: /hello
          method: get

plugins:
  - serverless-offline

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      sharedDb: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true
  seed:
    test:
      sources:
        - table: usersTable
          rawsources: [./fake-test-users.json]
  serverless-offline:
    host: 0.0.0.0
    port: 3000
    region: "ap-southeast-2"

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
